#! /usr/bin/env python
# -*- coding: utf-8 -*-

# ibus-el-agent --- helper program of IBus client for GNU Emacs
# Copyright (c) 2009 and onwards, S. Irie

# Author: S. Irie
# Maintainer: S. Irie
# Version: 0.0.2.62

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Commentary:

# IBus is a new input method framework under active development
# which is designed to overcome the limitations of SCIM.

# IBus uses D-Bus protocol for communication between the ibus-daemon
# and clients (engines, panel, config tools). Since the components
# run in separate processes there is enhanced modularity and stability.
# Client processes can be loaded, started and stopped independently.
# IBus supports Gtk2 and XIM, and has input method engines for anthy,
# chewing, hangul, m17n, pinyin, rawcode, and large tables. Engines
# and clients can be written in any language with a dbus binding.

# This program is IBus client for GNU Emacs. It is, however,
# not part of official IBus project.

# ChangeLog:

# 2010-05-29
#        * Version 0.1.0
#        * Initial release
# 2010-05-09
#        * Version 0.0.2
# 2010-04-12
#        * Version 0.0.1
#        * Initial experimental version

# Code:

import sys
import glib
import re

import ibus
from ibus import modifier

try:
    import Xlib.display
except ImportError:
    print "python-xlib library is required"
    exit(1)

display = Xlib.display.Display()

########################################################################
# Connect to IBus daemon
########################################################################

try:
    bus = ibus.Bus()
except TypeError:
    import os
    import time
    if os.spawnlp(os.P_WAIT, "ibus-daemon", "ibus-daemon", "-d") == 0:
        for i in range(10):
            time.sleep(0.5)
            try:
                bus = ibus.Bus()
                break
            except TypeError:
                pass
        else:
            print '(error "Failed to connect with ibus-daemon")'
            exit(1)
    else:
        print '(error "Failed to launch ibus-daemon")'
        exit(1)

########################################################################
# Miscellaneous functions
########################################################################

def lisp_boolean(boolean):
    return "t" if boolean else "nil"

escape_regexp = re.compile(ur'(["\\])')

def escape_string(string):
    return escape_regexp.sub(ur'\\\1', string)

########################################################################
# Input Context
########################################################################

class IBusELInputContext(ibus.InputContext):

    def __init__(self, bus):
        self.__bus = bus
        self.__path = bus.create_input_context("IBusELInputContext")
        super(IBusELInputContext, self).__init__(bus, self.__path, True)

        self.id_no = 0
        self.lookup_table = None

        self.connect('commit-text', commit_text_cb)
        self.connect('update-preedit-text', update_preedit_text_cb)
        self.connect('show-preedit-text', show_preedit_text_cb)
        self.connect('hide-preedit-text', hide_preedit_text_cb)
        self.connect('update-auxiliary-text', update_auxiliary_text_cb)
        self.connect('show-auxiliary-text', show_auxiliary_text_cb)
        self.connect('hide-auxiliary-text', hide_auxiliary_text_cb)
        self.connect('update-lookup-table', update_lookup_table_cb)
        self.connect('show-lookup-table', show_lookup_table_cb)
        self.connect('hide-lookup-table', hide_lookup_table_cb)
        self.connect('page-up-lookup-table', page_up_lookup_table_cb)
        self.connect('page-down-lookup-table', page_down_lookup_table_cb)
        self.connect('cursor-up-lookup-table', cursor_up_lookup_table_cb)
        self.connect('cursor-down-lookup-table', cursor_down_lookup_table_cb)
        self.connect('enabled', enabled_cb)
        self.connect('disabled', disabled_cb)
        try:
            self.connect('forward-key-event', forward_key_event_cb)
        except TypeError:
            pass
        try:
            self.connect('delete-surrounding-text', delete_surrounding_text_cb)
        except TypeError:
            pass

########################################################################
# Callbacks
########################################################################

def commit_text_cb(ic, text):
    print '(ibus-commit-text-cb %d "%s")'% \
        (ic.id_no, escape_string(text.text).encode("utf-8"))

def update_preedit_text_cb(ic, text, cursor_pos, visible):
    attrs = ['%s %d %d %d'%
             (["nil", "'underline", "'foreground", "'background"][attr.type],
              attr.value & 0xffffff, attr.start_index, attr.end_index)
             for attr in text.attributes]
    print '(ibus-update-preedit-text-cb %d "%s" %d %s %s)'% \
        (ic.id_no, escape_string(text.text).encode("utf-8"),
         cursor_pos, lisp_boolean(visible), ' '.join(attrs))

def show_preedit_text_cb(ic):
    print '(ibus-show-preedit-text-cb %d)'%(ic.id_no)

def hide_preedit_text_cb(ic):
    print '(ibus-hide-preedit-text-cb %d)'%(ic.id_no)

def update_auxiliary_text_cb(ic, text, visible):
    print '(ibus-update-auxiliary-text-cb %d "%s" %s)'% \
        (ic.id_no, escape_string(text.text).encode("utf-8"),
         lisp_boolean(visible))

def show_auxiliary_text_cb(ic):
    print '(ibus-show-auxiliary-text-cb %d)'%(ic.id_no)

def hide_auxiliary_text_cb(ic):
    print '(ibus-hide-auxiliary-text-cb %d)'%(ic.id_no)

def update_lookup_table_cb(ic, lookup_table, visible):
    ic.lookup_table = lookup_table
    if visible:
        self.__show_lookup_table_cb(ic)
    else:
        self.__hide_lookup_table_cb(ic)

def show_lookup_table_cb(ic):
    print "(ibus-show-lookup-table-cb %d '(%s) %s)"% \
        (ic.id_no, escape_string(
            " ".join(map(lambda item : '"%s"'%item.text,
                         ic.lookup_table.get_candidates_in_current_page())
                     )).encode("utf-8"),
         ic.lookup_table.get_cursor_pos_in_current_page())

def hide_lookup_table_cb(ic):
    print '(ibus-hide-lookup-table-cb %d)'%(ic.id_no)

def page_up_lookup_table_cb(ic):
    print '(ibus-log "page up lookup table")'

def page_down_lookup_table_cb(ic):
    print '(ibus-log "page down lookup table")'

def cursor_up_lookup_table_cb(ic):
    print '(ibus-log "cursor up lookup table")'

def cursor_down_lookup_table_cb(ic):
    print '(ibus-log "cursor down lookup table")'

def enabled_cb(ic):
    print '(ibus-status-changed-cb %d "%s")'%(ic.id_no, ic.get_engine().name)

def disabled_cb(ic):
    print '(ibus-status-changed-cb %d nil)'%ic.id_no

def forward_key_event_cb(ic, keyval, keycode, modifiers):
    print '(ibus-forward-key-event-cb %d %d %d %s)'% \
        (ic.id_no, keyval, modifiers & ~modifier.RELEASE_MASK,
         lisp_boolean(modifiers & modifier.RELEASE_MASK == 0))

def delete_surrounding_text_cb(ic, offset, n_chars):
    print '(ibus-delete-surrounding-text-cb %d %d %d)'% \
        (ic.id_no, offset, n_chars)

########################################################################
# Process methods from client
########################################################################

imcontexts = []

def create_imcontext():
    ic = IBusELInputContext(bus)
    try:
        ic.id_no = imcontexts.index(None)
        imcontexts[ic.id_no] = ic
    except ValueError:
        ic.id_no = len(imcontexts)
        imcontexts.append(ic)
    ic.set_capabilities(int('101001',2))
    print '(ibus-create-imcontext-cb %d)'%ic.id_no

def destroy_imcontext(id_no):
    imcontexts[id_no].destroy()
    if id_no == len(imcontexts) - 1:
        imcontexts.pop()
    else:
        imcontexts[id_no] = None

def process_key_event(id_no, keyval, modmask, backslash, pressed):
    if backslash:
        keycode = (display.keysym_to_keycode(backslash), 0)
    else:
        keycode = display.keysym_to_keycodes(keyval)[0]
        if keyval < 0x100 and keycode[1] & 1 != 0:
            modmask |= modifier.SHIFT_MASK
    if not pressed:
        modmask |= modifier.RELEASE_MASK
    handled = imcontexts[id_no].process_key_event(keyval, keycode[0] - 8, modmask)
    print '(ibus-process-key-event-cb %d %s)'%(id_no, lisp_boolean(handled))

def set_cursor_location(id_no, x, y, w, h):
    imcontexts[id_no].set_cursor_location(x, y, w, h)

def focus_in(id_no):
    imcontexts[id_no].focus_in()

def focus_out(id_no):
    imcontexts[id_no].focus_out()
    print '()' # Dummy response

def reset(id_no):
    imcontexts[id_no].reset()

def enable(id_no):
    imcontexts[id_no].enable()

def disable(id_no):
    imcontexts[id_no].disable()

def set_engine(id_no, name):
    for engine in bus.list_active_engines():
        if name == '%s'%engine.name:
            imcontexts[id_no].set_engine(engine)
            break
    else:
        enable(id_no)

########################################################################
# Experiment
########################################################################

def list_active_engines():
    print '(ibus-log "active engines: %s")'% \
        ' '.join('%s'%i.name for i in bus.list_active_engines())

########################################################################
# Main loop
########################################################################

class IBusModeMainLoop(glib.MainLoop):

    def __init__(self, bus):
        super(IBusModeMainLoop, self).__init__()
        bus.connect("disconnected", self.__disconnected_cb)

    def __disconnected_cb(self, *args):
        print '(ibus-log "disconnected")'
        exit()

    def __start_cb(self):
        print '(setq started t)'
        print 'Agent successfully started for display "%s"'% \
            display.get_display_name()
        return False

    def __stdin_cb(self, fd, condition):
        try:
            exec sys.stdin.readline()
        except:
            import traceback
            print '(error "%s")'%traceback.format_exc().replace('"', '\\"')
        return True

    def run(self):
        glib.idle_add(self.__start_cb)
        glib.io_add_watch(0, glib.IO_IN, self.__stdin_cb)
        while True:
            try:
                super(IBusModeMainLoop, self).run()
            except:
                import traceback
                print '(error "%s")'%traceback.format_exc().replace('"', '\\"')
            else:
                break
        for ic in imcontexts:
            if ic:
                ic.destroy()


if __name__ == "__main__":

    mainloop = IBusModeMainLoop(bus)
    mainloop.run()
